name: build-site
on: push

jobs:
  build-site:
    name: Update and deploy site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install -r requirements.txt;
    - name: Build site
      run: |
        python main.py
    - name: Deploy to pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: public
